name: go_work
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  kiwi: ^5.0.0
  go_router: ^14.8.1
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0

  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  test: ^1.25.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  kiwi_generator: ^4.2.1
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
